"""Increase roles.name column length from 16 to 50

Revision ID: ab36a60ff1e6
Revises: a7c9d2e4f1b6
Create Date: 2026-06-21 20:13:26.906086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab36a60ff1e6'
down_revision = 'a7c9d2e4f1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOCAL', 'GOOGLE', 'FACEBOOK', 'APPLE', name='authprovider'),
               existing_nullable=False)

    with op.batch_alter_table('print_product_categories', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('print_product_types', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('print_products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index('ix_print_products_vendor_product_id')
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_index('ix_product_options_product_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='userstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING_VERIFICATION'"))
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_users_email_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email_address', ['email_address'], unique=1)
        batch_op.alter_column('billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='userstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING_VERIFICATION'"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.create_index('ix_product_options_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('print_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_print_products_vendor_product_id', ['vendor_product_id'], unique=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    with op.batch_alter_table('print_product_types', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    with op.batch_alter_table('print_product_categories', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('LOCAL', 'GOOGLE', 'FACEBOOK', 'APPLE', name='authprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
